[package]
name = "parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.17"
tree-sitter = "0.20.10"
tree-sitter-fminus = { path = "../tree-sitter-fminus" }
